/**
 * JoyGames HR Portal - Initial Seed Data
 * Dữ liệu mẫu nhân sự chuẩn cho studio phát hành và phát triển Game JoyGames
 */

const JOYGAMES_DEPARTMENTS = [
  'Ban Giám Đốc',
  'Lập Trình Game (Game Dev)',
  'Thiết Kế Game (Game Design)',
  'Đồ Họa & Animation (Art 2D/3D)',
  'Vận Hành Game & LiveOps',
  'Marketing & Tăng Trưởng (UA)',
  'Chăm Sóc Khách Hàng (CSKH & Community)',
  'Hành Chính & Nhân Sự (HR & Admin)',
  'Tài Chính & Kế Toán'
];

const JOYGAMES_PROJECTS_DATA = [
  { code: 'HKHT', name: 'Haki Huyền Thoại', phase: 'LiveOps' },
  { code: 'PXDC', name: 'Pixel Đại Chiến', phase: 'LiveOps' },
  { code: 'B21', name: 'Dự Án Mới B21 (ARPG)', phase: 'Production (Sprint)' },
  { code: 'NAP', name: 'Cổng Nạp & Tài Khoản (Nap.Joyplay)', phase: 'LiveOps' },
  { code: 'CARD-TM', name: 'Dự Án Thần Ma (Card Battle)', phase: 'Pre-production' },
  { code: 'ALL', name: 'Khối Vận Hành Chung (All Projects)', phase: 'LiveOps' }
];

const JOYGAMES_PROJECTS = JOYGAMES_PROJECTS_DATA.map(p => p.name);

const DOCUMENT_TYPES = [
  { key: 'cccd_front', label: 'CCCD Mặt Trước', required: true, icon: 'badge' },
  { key: 'cccd_back', label: 'CCCD Mặt Sau', required: true, icon: 'badge' },
  { key: 'contract', label: 'Hợp Đồng Lao Động Ký Duyệt', required: true, icon: 'description' },
  { key: 'cv', label: 'Sơ Yếu Lý Lịch / CV Tuyển Dụng', required: true, icon: 'contact_page' },
  { key: 'degree', label: 'Bằng Cấp / Chứng Chỉ Chuyên Môn', required: false, icon: 'school' },
  { key: 'health_cert', label: 'Giấy Khám Sức Khỏe', required: true, icon: 'medical_services' },
  { key: 'nda', label: 'Cam Kết Bảo Mật Thông Tin (NDA JoyGames)', required: true, icon: 'verified_user' }
];

const JOYGAMES_COMPANIES = [
  'JoyGames Studio (Hà Nội)',
  'JoyPlay Mobile (TP.HCM)',
  'JoyTech Labs'
];

const WORK_TYPES = [
  'Full Time',
  'Part Time',
  'Remote'
];

const EDUCATION_LEVELS = [
  'Đại học',
  'Cao đẳng',
  'Trung cấp',
  'Trung học phổ thông',
  'Sau đại học'
];

const MARITAL_STATUSES = [
  'Độc thân',
  'Đã có gia đình'
];

const INITIAL_EMPLOYEES = [
  {
    id: 'JG-0001',
    fullName: 'Nguyễn Tuấn Thành',
    gender: 'Nam',
    birthDate: '1991-08-14',
    phone: '0988 567 890',
    personalEmail: 'tuanthanh.dev@gmail.com',
    workEmail: 'thanh.nt@joygames.vn',
    idCard: '001091004523',
    idCardDate: '2021-04-12',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Hà Nội',
    address: 'Căn hộ 1502, Tòa Mulberry Lane, Mỗ Lao, Hà Đông, Hà Nội',
    department: 'Lập Trình Game (Game Dev)',
    position: 'Trưởng Nhóm Lập Trình (Lead Unity Developer)',
    level: 'Lead',
    gameProject: 'Haki Huyền Thoại',
    joinDate: '2021-03-01',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2021/018',
    contractStart: '2021-05-01',
    contractEnd: 'Không thời hạn',
    baseSalary: 42000000,
    allowance: 3500000,
    bankAccount: '19033458992011 - Techcombank Đông Đô',
    taxId: '8092147823',
    insuranceId: '0120938472',
    status: 'Đang làm việc',
    manager: 'Đặng Quốc Huy (Giám Đốc Kỹ Thuật)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    notes: 'Kỹ sư Unity chủ lực, có kinh nghiệm 8 năm tối ưu hóa performance game mobile trên iOS & Android.',
    milestones: [
      { date: '2021-03-01', title: 'Gia nhập JoyGames', desc: 'Vị trí Senior Unity Developer' },
      { date: '2022-06-15', title: 'Thăng cấp Team Lead', desc: 'Bổ nhiệm Trưởng nhóm Dev dự án Haki Huyền Thoại' },
      { date: '2023-12-20', title: 'Khen thưởng MVP Năm', desc: 'Thành tích đưa Haki Huyền Thoại vượt mốc 200,000 người chơi' }
    ],
    documents: [
      { id: 'doc-1', type: 'cccd_front', name: 'CCCD_NguyenTuanThanh_MatTruoc.jpg', fileType: 'JPG', fileSize: '1.8 MB', uploadDate: '2021-03-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-2', type: 'cccd_back', name: 'CCCD_NguyenTuanThanh_MatSau.jpg', fileType: 'JPG', fileSize: '1.9 MB', uploadDate: '2021-03-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-3', type: 'contract', name: 'HDLD_KhongThoiHan_JG0001.pdf', fileType: 'PDF', fileSize: '3.4 MB', uploadDate: '2021-05-02', status: 'verified', url: '' },
      { id: 'doc-4', type: 'cv', name: 'CV_Senior_Unity_Dev_NTT.pdf', fileType: 'PDF', fileSize: '1.2 MB', uploadDate: '2021-02-15', status: 'verified', url: '' },
      { id: 'doc-5', type: 'degree', name: 'BangDaiHoc_DHBKHN_CNTT.pdf', fileType: 'PDF', fileSize: '2.1 MB', uploadDate: '2021-03-05', status: 'verified', url: '' },
      { id: 'doc-6', type: 'health_cert', name: 'GiayKSK_DinhKy_2024.pdf', fileType: 'PDF', fileSize: '2.8 MB', uploadDate: '2024-04-10', status: 'verified', url: '' },
      { id: 'doc-7', type: 'nda', name: 'CamKetBaoMat_JoyGames_NTT.pdf', fileType: 'PDF', fileSize: '1.5 MB', uploadDate: '2021-03-01', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0002',
    fullName: 'Trần Mai Linh',
    gender: 'Nữ',
    birthDate: '1995-11-22',
    phone: '0977 123 456',
    personalEmail: 'mailinh.art@gmail.com',
    workEmail: 'linh.tm@joygames.vn',
    idCard: '038195009871',
    idCardDate: '2020-09-18',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Thanh Hóa',
    address: 'Số 45 Ngõ 120 Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
    department: 'Đồ Họa & Animation (Art 2D/3D)',
    position: 'Trưởng Nhóm Mỹ Thuật (Art Director)',
    level: 'Director',
    gameProject: 'Pixel Đại Chiến',
    joinDate: '2020-08-10',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2020/009',
    contractStart: '2020-10-10',
    contractEnd: 'Không thời hạn',
    baseSalary: 45000000,
    allowance: 4000000,
    bankAccount: '102874920199 - VietinBank Ba Đình',
    taxId: '8493021984',
    insuranceId: '0129384751',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    notes: 'Phụ trách phong cách nghệ thuật toàn bộ các game của JoyGames. Quản lý team 15 họa sĩ 2D/3D.',
    milestones: [
      { date: '2020-08-10', title: 'Gia nhập JoyGames', desc: 'Lead 2D Concept Artist' },
      { date: '2022-01-10', title: 'Thăng cấp Art Director', desc: 'Quản lý toàn bộ định hướng thẩm mỹ sản phẩm' }
    ],
    documents: [
      { id: 'doc-8', type: 'cccd_front', name: 'CCCD_TranMaiLinh_F.jpg', fileType: 'JPG', fileSize: '2.1 MB', uploadDate: '2020-08-11', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-9', type: 'cccd_back', name: 'CCCD_TranMaiLinh_B.jpg', fileType: 'JPG', fileSize: '2.0 MB', uploadDate: '2020-08-11', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-10', type: 'contract', name: 'HDLD_TranMaiLinh.pdf', fileType: 'PDF', fileSize: '3.1 MB', uploadDate: '2020-10-12', status: 'verified', url: '' },
      { id: 'doc-11', type: 'cv', name: 'Portfolio_CV_MaiLinh.pdf', fileType: 'PDF', fileSize: '15.4 MB', uploadDate: '2020-08-01', status: 'verified', url: '' },
      { id: 'doc-12', type: 'degree', name: 'BangDaiHoc_MyThuatCongNghiep.pdf', fileType: 'PDF', fileSize: '1.9 MB', uploadDate: '2020-08-15', status: 'verified', url: '' },
      { id: 'doc-13', type: 'health_cert', name: 'GiayKhamSucKhoe_2024.pdf', fileType: 'PDF', fileSize: '2.3 MB', uploadDate: '2024-05-18', status: 'verified', url: '' },
      { id: 'doc-14', type: 'nda', name: 'NDA_StudioGame_LinhTM.pdf', fileType: 'PDF', fileSize: '1.2 MB', uploadDate: '2020-08-10', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0003',
    fullName: 'Lê Hoàng Long',
    gender: 'Nam',
    birthDate: '1996-03-08',
    phone: '0912 345 678',
    personalEmail: 'long.lehoang@gmail.com',
    workEmail: 'long.lh@joygames.vn',
    idCard: '001096012399',
    idCardDate: '2021-08-20',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Hà Nội',
    address: 'Số 18 Phố Vọng, Hai Bà Trưng, Hà Nội',
    department: 'Thiết Kế Game (Game Design)',
    position: 'Chuyên Viên Cân Bằng Game (Lead Game Designer)',
    level: 'Lead',
    gameProject: 'Dự Án Mới B21 (ARPG)',
    joinDate: '2022-04-15',
    contractType: 'Chính thức (1 - 3 năm)',
    contractNumber: 'HĐLĐ-JG/2022/045',
    contractStart: '2022-06-15',
    contractEnd: '2025-06-14',
    baseSalary: 32000000,
    allowance: 2500000,
    bankAccount: '0491000123456 - Vietcombank Thăng Long',
    taxId: '8392019482',
    insuranceId: '0139485721',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    notes: 'Phụ trách Core Combat mechanics và Economy System cho dự án Game ARPG B21 bí mật chuẩn bị closed beta.',
    milestones: [
      { date: '2022-04-15', title: 'Gia nhập JoyGames', desc: 'Game Designer Dự án B21' }
    ],
    documents: [
      { id: 'doc-15', type: 'cccd_front', name: 'CCCD_LeHoangLong_Truoc.jpg', fileType: 'JPG', fileSize: '1.7 MB', uploadDate: '2022-04-16', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-16', type: 'cccd_back', name: 'CCCD_LeHoangLong_Sau.jpg', fileType: 'JPG', fileSize: '1.8 MB', uploadDate: '2022-04-16', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-17', type: 'contract', name: 'HDLD_3Nam_LeHoangLong.pdf', fileType: 'PDF', fileSize: '2.9 MB', uploadDate: '2022-06-16', status: 'verified', url: '' },
      { id: 'doc-18', type: 'cv', name: 'CV_GameDesigner_LongLH.pdf', fileType: 'PDF', fileSize: '1.4 MB', uploadDate: '2022-04-01', status: 'verified', url: '' },
      { id: 'doc-19', type: 'nda', name: 'CamKetBaoMatDuaAnB21_NDA.pdf', fileType: 'PDF', fileSize: '1.3 MB', uploadDate: '2022-04-15', status: 'verified', url: '' }
      // Lưu ý: Nhân sự này thiếu Bằng cấp và Giấy KSK -> để làm tính năng cảnh báo hồ sơ chưa đầy đủ
    ]
  },
  {
    id: 'JG-0004',
    fullName: 'Phạm Thu Trang',
    gender: 'Nữ',
    birthDate: '1997-05-19',
    phone: '0966 888 999',
    personalEmail: 'thutrang.hr@gmail.com',
    workEmail: 'trang.pt@joygames.vn',
    idCard: '001197003456',
    idCardDate: '2022-01-10',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Bắc Ninh',
    address: 'Chung cư Skylake, Phạm Hùng, Nam Từ Liêm, Hà Nội',
    department: 'Hành Chính & Nhân Sự (HR & Admin)',
    position: 'Chuyên Viên Nhân Sự & Quản Lý Hồ Sơ (HR Executive)',
    level: 'Senior',
    gameProject: 'Khối Vận Hành Chung (All Projects)',
    joinDate: '2022-02-10',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2022/012',
    contractStart: '2022-04-10',
    contractEnd: 'Không thời hạn',
    baseSalary: 22000000,
    allowance: 2000000,
    bankAccount: '19034567891012 - Techcombank Keangnam',
    taxId: '8594038192',
    insuranceId: '0149583726',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    notes: 'Quản trị viên hệ thống HR Portal. Phụ trách C&B, tuyển dụng talent mảng Game và lưu trữ hồ sơ pháp lý.',
    milestones: [
      { date: '2022-02-10', title: 'Gia nhập JoyGames', desc: 'HR Executive mảng Tuyển dụng & Onboarding' },
      { date: '2023-05-01', title: 'Ký HĐ không xác định thời hạn', desc: 'Đảm nhiệm chính mảng C&B và Hồ sơ lao động' }
    ],
    documents: [
      { id: 'doc-20', type: 'cccd_front', name: 'CCCD_PhamThuTrang_Truoc.jpg', fileType: 'JPG', fileSize: '1.9 MB', uploadDate: '2022-02-11', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-21', type: 'cccd_back', name: 'CCCD_PhamThuTrang_Sau.jpg', fileType: 'JPG', fileSize: '1.8 MB', uploadDate: '2022-02-11', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-22', type: 'contract', name: 'HDLD_PhamThuTrang_2022.pdf', fileType: 'PDF', fileSize: '3.2 MB', uploadDate: '2022-04-12', status: 'verified', url: '' },
      { id: 'doc-23', type: 'cv', name: 'CV_HR_Executive_TrangPT.pdf', fileType: 'PDF', fileSize: '1.1 MB', uploadDate: '2022-02-01', status: 'verified', url: '' },
      { id: 'doc-24', type: 'degree', name: 'BangDaiHoc_KinhTeQuocDan_QuanTriNhanLuc.pdf', fileType: 'PDF', fileSize: '2.4 MB', uploadDate: '2022-02-15', status: 'verified', url: '' },
      { id: 'doc-25', type: 'health_cert', name: 'GiayKSK_TrangPT_2024.pdf', fileType: 'PDF', fileSize: '2.0 MB', uploadDate: '2024-03-25', status: 'verified', url: '' },
      { id: 'doc-26', type: 'nda', name: 'NDA_JoyGames_TrangPT.pdf', fileType: 'PDF', fileSize: '1.0 MB', uploadDate: '2022-02-10', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0005',
    fullName: 'Hoàng Minh Quân',
    gender: 'Nam',
    birthDate: '1994-09-30',
    phone: '0904 555 777',
    personalEmail: 'minhquan.ops@gmail.com',
    workEmail: 'quan.hm@joygames.vn',
    idCard: '031094002931',
    idCardDate: '2021-12-05',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Hải Phòng',
    address: 'Số 12 Ngõ 88 Trung Kính, Cầu Giấy, Hà Nội',
    department: 'Vận Hành Game & LiveOps',
    position: 'Trưởng Nhóm Vận Hành (LiveOps Lead)',
    level: 'Lead',
    gameProject: 'Haki Huyền Thoại',
    joinDate: '2021-07-01',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2021/055',
    contractStart: '2021-09-01',
    contractEnd: 'Không thời hạn',
    baseSalary: 35000000,
    allowance: 3000000,
    bankAccount: '0021000987654 - Vietcombank Hà Nội',
    taxId: '8492018374',
    insuranceId: '0138472910',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    notes: 'Quản lý lịch trình bảo trì máy chủ, mở server mới, chuỗi event in-game và cân đối tỷ lệ quy đổi nạp.',
    milestones: [
      { date: '2021-07-01', title: 'Gia nhập JoyGames', desc: 'Game Operation Specialist' },
      { date: '2023-01-05', title: 'Thăng cấp Lead LiveOps', desc: 'Điều phối team Vận hành game Haki & Pixel' }
    ],
    documents: [
      { id: 'doc-27', type: 'cccd_front', name: 'CCCD_HoangMinhQuan_T.jpg', fileType: 'JPG', fileSize: '2.0 MB', uploadDate: '2021-07-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-28', type: 'cccd_back', name: 'CCCD_HoangMinhQuan_S.jpg', fileType: 'JPG', fileSize: '1.9 MB', uploadDate: '2021-07-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-29', type: 'contract', name: 'HDLD_HoangMinhQuan.pdf', fileType: 'PDF', fileSize: '3.0 MB', uploadDate: '2021-09-02', status: 'verified', url: '' },
      { id: 'doc-30', type: 'cv', name: 'CV_LiveOps_QuanHM.pdf', fileType: 'PDF', fileSize: '1.3 MB', uploadDate: '2021-06-20', status: 'verified', url: '' },
      { id: 'doc-31', type: 'degree', name: 'BangDaiHoc_DaiHocQuocGia.pdf', fileType: 'PDF', fileSize: '2.2 MB', uploadDate: '2021-07-10', status: 'verified', url: '' },
      { id: 'doc-32', type: 'health_cert', name: 'KSK_DinhKy_QuanHM.pdf', fileType: 'PDF', fileSize: '2.5 MB', uploadDate: '2024-04-15', status: 'verified', url: '' },
      { id: 'doc-33', type: 'nda', name: 'CamKetBaoMat_QuanHM.pdf', fileType: 'PDF', fileSize: '1.1 MB', uploadDate: '2021-07-01', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0006',
    fullName: 'Đỗ Thùy Dung',
    gender: 'Nữ',
    birthDate: '1998-12-04',
    phone: '0934 678 123',
    personalEmail: 'thuydung.mkt@gmail.com',
    workEmail: 'dung.dt@joygames.vn',
    idCard: '025198007621',
    idCardDate: '2022-03-14',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Quảng Ninh',
    address: 'Toà Roman Plaza, Tố Hữu, Nam Từ Liêm, Hà Nội',
    department: 'Marketing & Tăng Trưởng (UA)',
    position: 'Chuyên Viên Chạy Quảng Cáo Game (Performance Marketer)',
    level: 'Senior',
    gameProject: 'Pixel Đại Chiến',
    joinDate: '2023-01-15',
    contractType: 'Chính thức (1 - 3 năm)',
    contractNumber: 'HĐLĐ-JG/2023/005',
    contractStart: '2023-03-15',
    contractEnd: '2026-03-14',
    baseSalary: 26000000,
    allowance: 2500000,
    bankAccount: '108876543210 - MB Bank Mỹ Đình',
    taxId: '8695028471',
    insuranceId: '0148593021',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a171ed2820ce?auto=format&fit=crop&w=400&q=80',
    notes: 'Quản lý ngân sách chạy ads TikTok, Facebook, Google Ads cho các chiến dịch ra mắt server mới và sự kiện game lớn.',
    milestones: [
      { date: '2023-01-15', title: 'Gia nhập JoyGames', desc: 'Performance Marketing Specialist' },
      { date: '2023-11-20', title: 'Chiến dịch xuất sắc', desc: 'Đạt CPI tối ưu kỷ lục chiến dịch Pixel Đại Chiến Mùa 2' }
    ],
    documents: [
      { id: 'doc-34', type: 'cccd_front', name: 'CCCD_DoThuyDung_Truoc.jpg', fileType: 'JPG', fileSize: '2.2 MB', uploadDate: '2023-01-16', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-35', type: 'cccd_back', name: 'CCCD_DoThuyDung_Sau.jpg', fileType: 'JPG', fileSize: '2.1 MB', uploadDate: '2023-01-16', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-36', type: 'contract', name: 'HDLD_DoThuyDung_3Nam.pdf', fileType: 'PDF', fileSize: '3.3 MB', uploadDate: '2023-03-16', status: 'verified', url: '' },
      { id: 'doc-37', type: 'cv', name: 'CV_DoThuyDung_Marketing.pdf', fileType: 'PDF', fileSize: '1.5 MB', uploadDate: '2023-01-02', status: 'verified', url: '' },
      { id: 'doc-38', type: 'health_cert', name: 'GiayKSK_DungDT_2024.pdf', fileType: 'PDF', fileSize: '2.0 MB', uploadDate: '2024-02-20', status: 'verified', url: '' },
      { id: 'doc-39', type: 'nda', name: 'NDA_JoyGames_DoThuyDung.pdf', fileType: 'PDF', fileSize: '1.2 MB', uploadDate: '2023-01-15', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0007',
    fullName: 'Bùi Anh Tuấn',
    gender: 'Nam',
    birthDate: '1999-07-25',
    phone: '0979 246 810',
    personalEmail: 'tuanba.unity@gmail.com',
    workEmail: 'tuan.ba@joygames.vn',
    idCard: '001199008912',
    idCardDate: '2022-09-08',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Hà Nội',
    address: 'Số 95 Cầu Giấy, Quan Hoa, Cầu Giấy, Hà Nội',
    department: 'Lập Trình Game (Game Dev)',
    position: 'Lập Trình Viên Unity (Junior Game Dev)',
    level: 'Junior',
    gameProject: 'Haki Huyền Thoại',
    joinDate: '2024-02-01',
    contractType: 'Thử việc',
    contractNumber: 'HĐTV-JG/2024/008',
    contractStart: '2024-02-01',
    contractEnd: '2024-04-01',
    baseSalary: 16000000,
    allowance: 1500000,
    bankAccount: '19036789120391 - Techcombank Cầu Giấy',
    taxId: '8792019385',
    insuranceId: 'Chưa có',
    status: 'Thử việc',
    manager: 'Nguyễn Tuấn Thành (Lead Unity Developer)',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    notes: 'Tốt nghiệp Học viện Bưu chính Viễn thông. Nhanh nhẹn, đang tiếp nhận module UI và Event mini-game.',
    milestones: [
      { date: '2024-02-01', title: 'Bắt đầu thử việc', desc: 'Thử việc 2 tháng tại team Client Dev' }
    ],
    documents: [
      { id: 'doc-40', type: 'cccd_front', name: 'CCCD_BuiAnhTuan_T.jpg', fileType: 'JPG', fileSize: '1.6 MB', uploadDate: '2024-02-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-41', type: 'contract', name: 'HD_ThuViec_BuiAnhTuan.pdf', fileType: 'PDF', fileSize: '2.4 MB', uploadDate: '2024-02-02', status: 'verified', url: '' },
      { id: 'doc-42', type: 'cv', name: 'CV_TuanBA_Junior.pdf', fileType: 'PDF', fileSize: '1.1 MB', uploadDate: '2024-01-15', status: 'verified', url: '' },
      { id: 'doc-43', type: 'nda', name: 'NDA_BaoMatCode_TuanBA.pdf', fileType: 'PDF', fileSize: '1.2 MB', uploadDate: '2024-02-01', status: 'verified', url: '' }
      // Còn thiếu CCCD mặt sau và Giấy khám sức khỏe!
    ]
  },
  {
    id: 'JG-0008',
    fullName: 'Vũ Đức Nam',
    gender: 'Nam',
    birthDate: '1987-04-18',
    phone: '0903 222 333',
    personalEmail: 'ducnam.joygames@gmail.com',
    workEmail: 'nam.vd@joygames.vn',
    idCard: '001087000108',
    idCardDate: '2021-05-10',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Hà Nội',
    address: 'Biệt thự BT04, Khu Ngoại Giao Đoàn, Bắc Từ Liêm, Hà Nội',
    department: 'Ban Giám Đốc',
    position: 'Tổng Giám Đốc (Chief Executive Officer - CEO)',
    level: 'Director',
    gameProject: 'Khối Vận Hành Chung (All Projects)',
    joinDate: '2019-01-01',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2019/001',
    contractStart: '2019-01-01',
    contractEnd: 'Không thời hạn',
    baseSalary: 85000000,
    allowance: 10000000,
    bankAccount: '0011001239876 - Vietcombank Sở Giao Dịch',
    taxId: '8012938471',
    insuranceId: '0119283746',
    status: 'Đang làm việc',
    manager: 'Hội Đồng Quản Trị JoyGames',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    notes: 'Sáng lập và điều hành JoyGames. Định hướng chiến lược phát triển studio game và mạng lưới đối tác phát hành.',
    milestones: [
      { date: '2019-01-01', title: 'Thành lập JoyGames', desc: 'Khởi đầu với 10 thành viên nòng cốt' },
      { date: '2023-10-15', title: 'Top Studio Triển Vọng', desc: 'Nhận giải thưởng Game Studio Phát Triển Nhanh' }
    ],
    documents: [
      { id: 'doc-44', type: 'cccd_front', name: 'CCCD_VuDucNam_F.jpg', fileType: 'JPG', fileSize: '2.5 MB', uploadDate: '2021-05-12', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-45', type: 'cccd_back', name: 'CCCD_VuDucNam_B.jpg', fileType: 'JPG', fileSize: '2.3 MB', uploadDate: '2021-05-12', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-46', type: 'contract', name: 'HDLD_BoNhiem_CEO.pdf', fileType: 'PDF', fileSize: '4.1 MB', uploadDate: '2019-01-02', status: 'verified', url: '' },
      { id: 'doc-47', type: 'degree', name: 'BangThacSi_QuanTriKinhDoanh.pdf', fileType: 'PDF', fileSize: '2.9 MB', uploadDate: '2019-01-10', status: 'verified', url: '' },
      { id: 'doc-48', type: 'health_cert', name: 'KSK_2024_CEO.pdf', fileType: 'PDF', fileSize: '3.2 MB', uploadDate: '2024-01-15', status: 'verified', url: '' },
      { id: 'doc-49', type: 'nda', name: 'CamKetBaoMatToiCao_NDA.pdf', fileType: 'PDF', fileSize: '2.1 MB', uploadDate: '2019-01-01', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0009',
    fullName: 'Lê Thảo My',
    gender: 'Nữ',
    birthDate: '2001-06-12',
    phone: '0981 765 432',
    personalEmail: 'thaomy.cskh@gmail.com',
    workEmail: 'my.lt@joygames.vn',
    idCard: '015201004561',
    idCardDate: '2023-02-18',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Ninh Bình',
    address: 'Khu Đô Thị Kim Văn Kim Lũ, Hoàng Mai, Hà Nội',
    department: 'Chăm Sóc Khách Hàng (CSKH & Community)',
    position: 'Chuyên Viên Chăm Sóc Khách Hàng Game VIP',
    level: 'Middle',
    gameProject: 'Haki Huyền Thoại',
    joinDate: '2023-06-01',
    contractType: 'Chính thức (1 - 3 năm)',
    contractNumber: 'HĐLĐ-JG/2023/048',
    contractStart: '2023-08-01',
    contractEnd: '2025-07-31',
    baseSalary: 18000000,
    allowance: 2000000,
    bankAccount: '19035678912345 - Techcombank Linh Đàm',
    taxId: '8893019482',
    insuranceId: '0159382019',
    status: 'Đang làm việc',
    manager: 'Hoàng Minh Quân (LiveOps Lead)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    notes: 'Chăm sóc người chơi VIP, xử lý khiếu nại tài khoản nạp cổng nap.joyplay.vn và quản trị group cộng đồng 50.000 thành viên.',
    milestones: [
      { date: '2023-06-01', title: 'Gia nhập JoyGames', desc: 'CSKH Game Support' },
      { date: '2024-01-10', title: 'Nhân viên CSKH xuất sắc Quý 4', desc: 'Tỷ lệ hài lòng giải quyết ticket nạp đạt 99.2%' }
    ],
    documents: [
      { id: 'doc-50', type: 'cccd_front', name: 'CCCD_LeThaoMy_Truoc.jpg', fileType: 'JPG', fileSize: '1.9 MB', uploadDate: '2023-06-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-51', type: 'cccd_back', name: 'CCCD_LeThaoMy_Sau.jpg', fileType: 'JPG', fileSize: '1.8 MB', uploadDate: '2023-06-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-52', type: 'contract', name: 'HDLD_LeThaoMy_2023.pdf', fileType: 'PDF', fileSize: '2.8 MB', uploadDate: '2023-08-02', status: 'verified', url: '' },
      { id: 'doc-53', type: 'cv', name: 'CV_LeThaoMy_CSKH.pdf', fileType: 'PDF', fileSize: '1.2 MB', uploadDate: '2023-05-15', status: 'verified', url: '' },
      { id: 'doc-54', type: 'health_cert', name: 'GiayKSK_MyLT.pdf', fileType: 'PDF', fileSize: '1.9 MB', uploadDate: '2024-03-01', status: 'verified', url: '' },
      { id: 'doc-55', type: 'nda', name: 'NDA_JoyGames_LeThaoMy.pdf', fileType: 'PDF', fileSize: '1.0 MB', uploadDate: '2023-06-01', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0010',
    fullName: 'Đặng Quốc Huy',
    gender: 'Nam',
    birthDate: '1989-10-05',
    phone: '0918 899 998',
    personalEmail: 'quochuy.tech@gmail.com',
    workEmail: 'huy.dq@joygames.vn',
    idCard: '001089007812',
    idCardDate: '2021-07-22',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Nam Định',
    address: 'Khu Đô Thị An Hưng, Dương Nội, Hà Đông, Hà Nội',
    department: 'Lập Trình Game (Game Dev)',
    position: 'Giám Đốc Kỹ Thuật (Chief Technology Officer - CTO)',
    level: 'Director',
    gameProject: 'Khối Vận Hành Chung (All Projects)',
    joinDate: '2019-03-01',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2019/003',
    contractStart: '2019-03-01',
    contractEnd: 'Không thời hạn',
    baseSalary: 60000000,
    allowance: 5000000,
    bankAccount: '19028394857201 - Techcombank Thăng Long',
    taxId: '8093829102',
    insuranceId: '0110928374',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    notes: 'Kiến trúc sư hệ thống Server Game, hạ tầng Cloud Kubernetes, cổng thanh toán JoyGames billing gateway.',
    milestones: [
      { date: '2019-03-01', title: 'Gia nhập JoyGames', desc: 'Đồng sáng lập & CTO' },
      { date: '2021-09-01', title: 'Nâng cấp cụm Server Game', desc: 'Chịu tải 500.000 CCU đồng thời không downtime' }
    ],
    documents: [
      { id: 'doc-56', type: 'cccd_front', name: 'CCCD_DangQuocHuy_T.jpg', fileType: 'JPG', fileSize: '2.4 MB', uploadDate: '2021-07-25', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-57', type: 'cccd_back', name: 'CCCD_DangQuocHuy_S.jpg', fileType: 'JPG', fileSize: '2.3 MB', uploadDate: '2021-07-25', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-58', type: 'contract', name: 'HDLD_BoNhiem_CTO.pdf', fileType: 'PDF', fileSize: '3.8 MB', uploadDate: '2019-03-02', status: 'verified', url: '' },
      { id: 'doc-59', type: 'degree', name: 'BangKySu_DaiHocBachKhoa.pdf', fileType: 'PDF', fileSize: '2.5 MB', uploadDate: '2019-03-10', status: 'verified', url: '' },
      { id: 'doc-60', type: 'health_cert', name: 'GiayKSK_HuyDQ_2024.pdf', fileType: 'PDF', fileSize: '2.7 MB', uploadDate: '2024-02-12', status: 'verified', url: '' },
      { id: 'doc-61', type: 'nda', name: 'CamKetBaoMat_CTO_DangQuocHuy.pdf', fileType: 'PDF', fileSize: '1.9 MB', uploadDate: '2019-03-01', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0011',
    fullName: 'Ngô Kim Ngân',
    gender: 'Nữ',
    birthDate: '1993-01-20',
    phone: '0945 111 222',
    personalEmail: 'kimngan.acc@gmail.com',
    workEmail: 'ngan.nk@joygames.vn',
    idCard: '001193006782',
    idCardDate: '2022-04-10',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Thái Bình',
    address: 'Số 36 Nguyễn Thị Thập, Trung Hòa Nhân Chính, Cầu Giấy, Hà Nội',
    department: 'Tài Chính & Kế Toán',
    position: 'Kế Toán Trưởng (Chief Accountant)',
    level: 'Lead',
    gameProject: 'Khối Vận Hành Chung (All Projects)',
    joinDate: '2020-05-15',
    contractType: 'Chính thức (Không thời hạn)',
    contractNumber: 'HĐLĐ-JG/2020/015',
    contractStart: '2020-07-15',
    contractEnd: 'Không thời hạn',
    baseSalary: 38000000,
    allowance: 3000000,
    bankAccount: '0011004567890 - BIDV Hà Nội',
    taxId: '8291039485',
    insuranceId: '0129384019',
    status: 'Đang làm việc',
    manager: 'Vũ Đức Nam (Tổng Giám Đốc)',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80',
    notes: 'Quản lý doanh thu cổng nạp thẻ, đối soát cổng thanh toán ngân hàng/ví điện tử và quyết toán thuế thu nhập DN.',
    milestones: [
      { date: '2020-05-15', title: 'Gia nhập JoyGames', desc: 'Kế toán tổng hợp' },
      { date: '2021-11-01', title: 'Bổ nhiệm Kế toán trưởng', desc: 'Chịu trách nhiệm toàn bộ hệ thống tài chính kế toán' }
    ],
    documents: [
      { id: 'doc-62', type: 'cccd_front', name: 'CCCD_NgoKimNgan_T.jpg', fileType: 'JPG', fileSize: '2.1 MB', uploadDate: '2022-04-12', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-63', type: 'cccd_back', name: 'CCCD_NgoKimNgan_S.jpg', fileType: 'JPG', fileSize: '2.0 MB', uploadDate: '2022-04-12', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-64', type: 'contract', name: 'HDLD_NgoKimNgan.pdf', fileType: 'PDF', fileSize: '3.1 MB', uploadDate: '2020-07-16', status: 'verified', url: '' },
      { id: 'doc-65', type: 'cv', name: 'CV_NgoKimNgan_ChiefAccountant.pdf', fileType: 'PDF', fileSize: '1.3 MB', uploadDate: '2020-05-01', status: 'verified', url: '' },
      { id: 'doc-66', type: 'degree', name: 'ChungChiKTT_BoTaiChinh.pdf', fileType: 'PDF', fileSize: '2.6 MB', uploadDate: '2020-05-20', status: 'verified', url: '' },
      { id: 'doc-67', type: 'health_cert', name: 'KSK_2024_NganNK.pdf', fileType: 'PDF', fileSize: '2.2 MB', uploadDate: '2024-04-05', status: 'verified', url: '' },
      { id: 'doc-68', type: 'nda', name: 'CamKetBaoMatTaiChinh_JoyGames.pdf', fileType: 'PDF', fileSize: '1.4 MB', uploadDate: '2020-05-15', status: 'verified', url: '' }
    ]
  },
  {
    id: 'JG-0012',
    fullName: 'Trịnh Hoàng Yến',
    gender: 'Nữ',
    birthDate: '2002-11-14',
    phone: '0983 456 999',
    personalEmail: 'hoangyen.anim@gmail.com',
    workEmail: 'yen.th@joygames.vn',
    idCard: '019202008765',
    idCardDate: '2023-08-15',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: 'Thái Nguyên',
    address: 'Ký túc xá FPT Polytechnic, Mỹ Đình, Hà Nội',
    department: 'Đồ Họa & Animation (Art 2D/3D)',
    position: 'Thực Tập Sinh 2D Spine Animation (Intern)',
    level: 'Intern',
    gameProject: 'Pixel Đại Chiến',
    joinDate: '2024-03-01',
    contractType: 'Thực tập sinh',
    contractNumber: 'HĐTTS-JG/2024/003',
    contractStart: '2024-03-01',
    contractEnd: '2024-06-01',
    baseSalary: 6000000,
    allowance: 1000000,
    bankAccount: '19039988776655 - Techcombank Mỹ Đình',
    taxId: 'Chưa có',
    insuranceId: 'Chưa có',
    status: 'Đang làm việc',
    manager: 'Trần Mai Linh (Art Director)',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    notes: 'Thực tập sinh tiềm năng về Animation xương Spine 2D. Đã dựng được animation di chuyển và tung chiêu cho 5 tướng game.',
    milestones: [
      { date: '2024-03-01', title: 'Bắt đầu kỳ thực tập', desc: 'Thực tập sinh 3 tháng mảng 2D Spine Game Art' }
    ],
    documents: [
      { id: 'doc-69', type: 'cccd_front', name: 'CCCD_TrinhHoangYen_F.jpg', fileType: 'JPG', fileSize: '1.7 MB', uploadDate: '2024-03-02', status: 'verified', url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
      { id: 'doc-70', type: 'contract', name: 'HopDongThucTap_HoangYen.pdf', fileType: 'PDF', fileSize: '2.1 MB', uploadDate: '2024-03-02', status: 'verified', url: '' },
      { id: 'doc-71', type: 'cv', name: 'CV_Portfolio_HoangYen.pdf', fileType: 'PDF', fileSize: '8.4 MB', uploadDate: '2024-02-20', status: 'verified', url: '' },
      { id: 'doc-72', type: 'nda', name: 'CamKetBaoMat_ThucTapSinh_YenTH.pdf', fileType: 'PDF', fileSize: '1.1 MB', uploadDate: '2024-03-01', status: 'verified', url: '' }
      // Còn thiếu CCCD mặt sau và Giấy khám sức khỏe!
    ]
  }
];
